# Generated by Django 5.0.3 on 2024-03-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, verbose_name='Номер машины')),
                ('capacity', models.IntegerField(verbose_name='Грузоподъемность')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.location', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
