# Generated by Django 5.0.3 on 2024-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Грузоподъемность'),
        ),
    ]
