# Generated by Django 5.0.3 on 2024-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('truck', '0004_alter_truck_capacity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='truck',
            index=models.Index(fields=['number'], name='truck_truck_number_f53534_idx'),
        ),
    ]
