# Generated by Django 5.0.3 on 2024-03-26 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Вес груза должен быть не меньше 1!'), django.core.validators.MaxValueValidator(1000, message='Вес груза должна быть не больше 1000!')], verbose_name='Вес груза')),
                ('description', models.TextField(verbose_name='Описание груза')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cargo', to='location.location', verbose_name='Локация доставки груза')),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up_cargo', to='location.location', verbose_name='Локация нахождения груза')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
    ]
